# Generated by Django 2.1.2 on 2018-11-06 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('descripcion', models.TextField()),
                ('code_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('telephone_number', models.CharField(max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=True, to='hotel.Company')),
                ('created_by', models.ForeignKey(on_delete=False, related_name='hotel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=False, related_name='hotel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=0)),
                ('bedOption', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('view', models.CharField(max_length=255)),
                ('total_rooms', models.CharField(max_length=255)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='StatusReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(choices=[('R', 'RESERVED'), ('RQ', 'REQUESTED'), ('A', 'AVAILABLE'), ('P', 'PROGRESS')], max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(choices=[('DB', 'Dirty_Busy'), ('CB', 'Clean_Busy'), ('DE', 'Dirty_Empty'), ('CE', 'Client_Empty')], max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='type_room/')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='last_status',
            field=models.ForeignKey(on_delete=False, related_name='room_status', to='hotel.StatusRoom'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=False, to='hotel.TypeRoom'),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.ManyToManyField(related_name='room_statuses', to='hotel.StatusRoom'),
        ),
    ]
